# 7장 비동기 호출

## 7.3 API 에러 핸들링
코드에서 발생할 수 있는 에러 상황에 대해 명시적인 코드를 작성하면 유지보수가 용이해지고, 사용자에게도 구체적인 에러 상황을 전달할 수 있다.

### 7.3.1 타입 가드 활용하기
Axios 라이브러리에서 Axios 에러에 대해 isAxiosError라는 타입 가드를 제공하고 있다.
- 서버 에러 명확하게 표시
- 서버에서 내려주는 에러 응답 객체에 대해 구체적으로 정의함으로써 에러 객체가 어떤 속서을 가졌는지 파악할 수 있다.
```jsx
interface ErrorResponse {
  status: string;
  serverDateTime: string;
  errorCode: string;
  errorMessage: string;
}
```
- ErrorResponse 인터페이스를 사용해서 처리해야할 Axios 에러 형태는 AxiosError로 작성할 수 있고, 아래와 같이 타입 가드를 명시적으로 작성할 수 있다.
```jsx
function isServerError(error: unknown): error is AxiosError<ErrorResponse> {
  return axios.isAxiosError(error);
}
```
> 참고로 사용자 정의 타입 가드를 정의할 때는 타입 가드 함수의 반환 타입으로 parameterName is Type 형태의 타입 명제를 정의해주는게 좋다.

> 이 때 parameterName은 타입 가드 함수의 시그니처에 포함된 매개변수여야한다.

```jsx
const onClickDeleteHistoryButton = async (id: string) => {
  try {
  	await axios.post("https://...", { id });
  	alert("주문 내역이 삭제되었습니다.");
  } catch (error: unknown) {
  	if (isServerError(e) && e.response && e.response.data.errorMessage) {
  		// 서버 에러일 때의 처리임을 명시적으로 알 수 있음
  		setErrorMessage(e.response.data.errorMessage);
  		return;
  	}
  	setErrorMessage("일시적인 에러가 발생했습니다. 잠시 후 다시 시도해주세요");
  }
};
```
- 이렇게 타입 가드를 활용하면 서버 에러를 명시적으로 확인할 수 있다.
  
### 7.3.2 에러 서브클래싱 하기
- 서브클래싱: 기존(상위 또는 부모) 클래스를 확장하여 새로운(하위 또는 자식) 클래스를 만드는 과정을 한다.
- 단순히 에러 메세지를 얼럿을 사용하여 사용자에게 표시해주면 사용자는 어떤 에러가 발생한지 판단할 수 있지만, 개발자 입장에서는 구분할 수 없다.
- 서브클래싱을 활용하면 에러가 발생했을때 코드상에서 바로 확인할 수 있다.
- 또한 에러 인스턴스가 뭔지에 따라 에러 처리방식도 다르게 구현할 수 있다.
```jsx
// 기본 API 오류 클래스
class APIError extends Error {
  constructor(message: string) {
    super(message);
    this.name = this.constructor.name;
    Error.captureStackTrace(this, this.constructor);
  }
}

// 특정 상태 코드를 처리하는 서브클래스
class HTTPError extends APIError {
  statusCode: number;

  constructor(statusCode: number, message: string) {
    super(message);
    this.statusCode = statusCode;
  }
}

// 404 오류 처리를 위한 서브클래스
class NotFoundError extends HTTPError {
  constructor(message = 'Not Found') {
    super(404, message);
  }
}
```
```jsx
class OrderHttpError extends Error {
  private readonly privateResponse: AxiosResponse<ErrorResponse> | undefined;
  
  constructor(message?: string, response?: AxiosResponse<ErrorResponse>) {
    super(message);
    this.name = "OrderHttpError";
    this.privateResponse = response;
  }
  
  get response(): AxiosResponse<ErrorResponse> | undefined {
    return this.privateResponse;
  }
}

class NetworkError extends Error {
  constructor(message = ""){
    super(message);
    this.name = "NetworkError";
  }
}

class UnauthorizeError extends Error {
  constructor(message?: string, response?: AxiosResponse<ErrorResponse>) {
    super(message, response);
    this.name = "UnauthorizeError";
  }
}
```
- 이처럼 에러를 서브클래싱해서 표현하면 명시적으로 에러 처리를 할 수 있다.
- error instanceof OrderHttpError와 같이 작성된 타입 가드문을 통해 코드상에서 에러 핸들링에 대한 부분을 한눈에 볼 수 있다.

### 7.3.3 인터셉터를 활용한 에러 처리
Axios 같은 페칭 라이브러리는 인터셉터 기능을 제공한다. 사용하면 HTTP 에러에 일관된 로직을 적용할 수 있다.
```jsx
const httpErrorHandler = ( error: AxiosError<ErrorResponse> | Error ): Promise<Error> = {
  (error) => {
  	// 401에러 인 경우 로그인 페이지로 이동
  	if (error.response && error.response.status === 401) {
  		window.location.href = `${backOfficeAuthHost}/login?targetUrl=${window.location.href}`;
  	}
  	return Promise.reject(error);
  };
};
  
orderApiRequester.interceptors.response.use(
  	(response: AxiosResponse) => response,
  	httpErrorHandler
);
```

### 7.3.4 에러 바운더리를 활용한 에러 처리
- 에러 바운더리: 리액트 컴포넌트 트리에서 에러가 발생할 때 공통으로 에러를 처리하는 리액트 컴포넌트
  - 사용하면 리액트 컴포넌트 트리 하위에 있는 컴포넌트에서 발생한 에러를 캐치하고, 해당 에러를 가장 가까운 부모 에러 바운더리에서 처리할 수 있다.
  - 에러가 발생한 컴포넌트 대신 에러 처리를 하거나 예상치 못한 에러를 공통 처리할 때 사용
```jsx
import React, { ErrorInfo } from "react"
import ErrorPage from "pages/ErrorPage";

interface ErrorBoundaryProps {}

interface ErrorBoundaryState {
  hasError: boolean;  //오류 발생 여부 관리
}
  
class ErrorBoundary extends React.Component<
  ErrorBoundaryProps,
  ErrorBoundaryState
> {
  constructor(props: ErrorBoundaryProps) {
  	super(props);
  	this.state = { hasError: false };  //초기 상태 설정
  }

  //오류 발생시 상태 변경
  static getDerivedStateFromError(): ErrorBoundaryState {
  	return { hasError: true };
  }

  //오류 로그 및 상태 업데이트
  componentDidCatch(error: Error, errorInfo: ErrorInfo): void {
  this.setStatae({ hasError: true });
  console.error(error, errorInfo);
 }
 //렌더링 
 render(): React.ReactNode {
  	const { children } = this.props;
  	const { hasError } = this.state;
    //오류가 있으면 <ErrorPage />를 보여주고, 없으면 자식 컴포넌트 렌더링
  	return hasError ? <ErrorPage /> : children;
 }
}
    
const App = ()=> {
  return (
  	<ErrorBoundary>
      	<OrderHistoryPage />
  	</ErrorBoundary>
  );
};
```
- OrderHistory 컴포넌트 내에서 처리되지 않은 에러처리가 있을 때 에러 바운더리에서 에러 페이지를 노출한다.
- 이외에도 에러 바운더리에 로그를 보내는 코드를 추가하여 예상치 못한 에러의 발생 여부를 추적할 수 있게 된다.
- React 앱에서 **에러가 발생했을 때 앱 전체가 다운되지 않고** 안전하게 에러 페이지를 보여주는 ErrorBoundary 패턴을 구현

### 7.3.5 상태 관리 라이브러리에서의 에러 처리
Redux의 경우 401, 403 에러 처럼 에러 상태를 관리하지 않고 처리할 수 있다면 바로 처리하고, 그렇지 않다면 reject로 넘겨준다. 이후 액션을 정의하면서 setApiCallError를 사용하여 에러를 상태로 처리한다.
```jsx
// API 호출에 관한 api call reducer
const apiCallSlice = createSlice({
  name: "apiCall",
  initialState, 
  reducers: {
  // API 호출 상태와 관련된 정보(status, url, method 등)를 저장
	setApiCall: (state, { payload: ( status, urlInfo } }) => {
	  /* API State를 채우는 logic */
    },
    // API 호출 실패 시 에러 정보를 저장.
    setApiCallError: (state, { payload }: PayloadAction<any>) => {
      state.error = payload;
    },
  },
});

const API = axios.create();

//  Axios 응답 인터셉터 설정
const setAxiosInterceptor = (store: EnhancedStore) => {
  /* 중복 코드 생략 */
  
  // onSuccess시 처리를 인터센터로 처리한다
  API.interceptors-response.use(
    (response: AxiosResponse) => {
	  const { method, url } = response.config;
	
      store.dispatch(
        setApiCall({
		  status: ApiCallStatus.None, // API 호출 상태를 `요청되지 않음`으로 변경
		  urlInfo: { url, method },
		})
      );
			
      return response?.data?.data || response?.data;
    },
  // 응답 에러 처리
	(error: AxiosError) => {
	    // 401 unauthorized
      if (error.response?.status === 401) {
        window.location.href = error.response.headers.location;
  	  	return;
  	  }
  	  // 403 forbidden 
  	  else if (error.response?.status === 403) {
  	    window.location.href = error.response.headers.location;
  	    return;
  	  }
      // 그 외에는 화면에 alert 띄우기
      else {
        message.error(`[서버 요청 에러]: ${error?.response?.data?.message}`);
  	  }
  	  
      // 에러 발생한 API에 대해서도 호출 상태를 초기화.
      const {
  		  config : { url, method },
  	  } = error;
  		
  	  store.dispatch(
  		  setApiCall({
  		    status: ApiCallStatus.None, // API 호출 상태를 요청되지 않음`으로 변경
          urlInfo: { url, method },
      	})
      );
        
      return Promise.reject(error);
    }
  );
};
```
- 저장된 에러는 컴포넌트에서 사용 가능
```jsx
const fetchMenu = createAsyncThunk(
  FETCH_MENU_REQUEST,
  async ({ shopId, menuId }: FetchMenu) => {
    try {
      const data = await api.fetchMenu(shopId, menuId);
      return data;
    } catch (error) {
      setApiCallError({ error });
    }
  }
);
```

### 7.3.6 react-query를 활용한 에러 처리
react-query나 swr과 같은 데이터 페칭 라이브러리를 사용하면 요청에 대한 상태를 반환해주기 때문에 요청 상태를 확인하기 쉽다.
- react-query 예시
```jsx
const JobComponent: React.FC = () => {
  	const { isError, error, isLoading, data } = useFetchJobList();
  	
  	if (isError) {
  		return <div>{`${error.message}가 발생했습니다. 나중에 다시 시도해주세요.`}</div>;
    }
  
  	if (isLoading) {
  		return <div>로딩 중입니다.</div>;
  	}
  
  	return <>{data.map((job) => <JobItem key={job.id} job={job} />)}</>;
};
```

### 7.3.7 그 밖의 에러 처리
- API 응답은 주로 성공 시 2xx 코드를, 실패 시 4xx, 5xx 코드를 반환한다.
  - 비즈니스 로직에서 유효성 검증에 의해 추가된 에러는 200응답과 함께 응답 바디에 별도의 상태 코드를 전달하기도 한다.
  - 이러한 상황에선 커스텀 에러를 처리하고 구현하는 방식에 대한 논의가 필요하다.
  - 하지만 이미 설계가 그렇게 되어있거나 레거시로 남아있지만 영향 범위가 넓어 대응할 수 없을 때 200번 대의 성공 응답에 대한 에러 처리가 필요할 수도 있다.
 
- 커스텀 에러를 사용하는 요청을 일괄적으로 에러로 처리하고 싶으면 Axios 등의 라이브러리 기능을 활용할 수 있다.
  - 특정 호스트에 대한 API requester를 별도로 선언하고 상태 코드 비교 로직을 인터셉터에 추가할 수 있다.


참고 자료
- https://velog.io/@geun99/%EC%9A%B0%EC%95%84%ED%95%9C-%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8-with-%EB%A6%AC%EC%95%A1%ED%8A%B8-7%EC%9E%A5-%EB%B9%84%EB%8F%99%EA%B8%B0-%ED%98%B8%EC%B6%9C-7.3-API-%EC%97%90%EB%9F%AC-%ED%95%B8%EB%93%A4%EB%A7%81
